#!/bin/bash
set -e

USERNAME=pywebdriver
GROUP=usbusers

# TODO create deb packages for these dependencies
echo "Update pip installation to the last version"
pip install pip --upgrade
echo "Installing python dependencies via pip"
pip install jcconv pif Flask-Babel Flask-cors Pillow
pip install git+https://github.com/akretion/py-xml-escpos.git@8.0-slip-support
pip install --pre pyusb

echo "Configure pywebdriver user and group"
groupadd -f $GROUP
if id -u $USERNAME &>/dev/null; then
    echo "$USERNAME already exists"
else
    adduser --no-create-home --system $USERNAME
fi
adduser $USERNAME $GROUP
adduser $USERNAME dialout

echo "Restarting udev"
service udev restart

echo "Starting pywebdriver supervisor service"
supervisorctl reread
supervisorctl add pywebdriver

echo "Reload Nginx"
service nginx reload
