#!/bin/bash
set -e

VERSION=$(lsb_release -sc)
SERVICE=pywebdriver

# Trusty specific
if [[ $VERSION == trusty ]]; then
    echo "Stoping $SERVICE supervisor service"
    supervisorctl stop $SERVICE
    supervisorctl remove $SERVICE
fi
